import AuthContainer from "@/components/Auth/AuthContainer";
import ForgotPasswordForm from "@/components/Forms/ForgotPassword";

export const metadata = {
	title: "TeamForFilm | Forgot Password",
	description: "Generated by create next app",
};

export default function ForgotPassword() {
	return (
		<AuthContainer>
			<ForgotPasswordForm />
		</AuthContainer>
	);
}
