import AuthContainer from "@/components/Auth/AuthContainer";
import ForgotPasswordForm from "@/components/Forms/ForgotPassword";

export const metadata = {
	title: "TeamForFilm | Forgot Password",
	description: "Generated by create next app",
};

export default function ForgotPassword() {
	return (
		<AuthContainer heading="Forgot Password" subHeading="" footerHeading="Back to Log In?" footerLinkText="Log In" footerLink="/login">
			<ForgotPasswordForm />
		</AuthContainer>
	);
}
