import AuthContainer from "@/components/Auth/AuthContainer";
import RegistrationForm from "@/components/Forms/RegistrationForm";

export const metadata = {
	title: "TeamForFilm | Registration",
	description: "Generated by create next app",
};

export default function Register() {
	return (
		<>
			<AuthContainer>
				<RegistrationForm />
			</AuthContainer>
		</>
	);
}
