export const projectGenre = [
	"Documentary films",
	"Educational Videos",
	"Feature Films",
	"Music Videos",
	"News Anchoring",
	"Online Content",
	"Public Service Announcements",
	"Reality Shows",
	"Short Films",
	"Theater Art/Drama",
	"TV Commercials/Adverts",
	"TV/Web Series",
	"Voice Over/Narration",
];

export const filmDepartments = [
	{ value: "actor", label: "Actor" },
	{ value: "actionStuntCoordinator", label: "Action/Stunt Coordinator" },
	{ value: "animalTrainerHandler", label: "Animal Trainer/Handler" },
	{ value: "assistantDirector", label: "Assistant Director (1st AD, 2nd AD)" },
	{ value: "boomOperatorSoundRecordist", label: "Boom Operator/Sound Recordist" },
	{ value: "castingDirector", label: "Casting Director" },
	{ value: "cinematographer", label: "Cinematographer/Director of Photography (DP)" },
	{ value: "colorist", label: "Colorist" },
	{ value: "musicProducerComposer", label: "Music Producer/Composer" },
	{ value: "costumeDesignerWardrobe", label: "Costume Designer/Wardrobe" },
	{ value: "craftServiceCatering", label: "Craft Service/Catering" },
	{ value: "dialogueEditor", label: "Dialogue Editor" },
	{ value: "digitalEffectsArtist", label: "Digital Effects Artist" },
	{ value: "director", label: "Director" },
	{ value: "distributionCoordinator", label: "Distribution Coordinator" },
	{ value: "editor", label: "Editor" },
	{ value: "foleyArtistSoundEffectsEditor", label: "Foley Artist/Sound Effects Editor" },
	{ value: "gafferGrip", label: "Gaffer/Grip" },
	{ value: "locationManagerScout", label: "Location Manager/Scout" },
	{ value: "locationSoundMixer", label: "Location Sound Mixer" },
	{ value: "makeupHairStylist", label: "Makeup/Hair Stylist" },
	{ value: "marketingPublicityCoordinator", label: "Marketing/Publicity Coordinator" },
	{ value: "musicProducer", label: "Music Producer" },
	{ value: "postProductionSupervisor", label: "Post-production Supervisor" },
	{ value: "producer", label: "Producer" },
	{ value: "productionDesignerArtDirector", label: "Production Designer/Art Director" },
	{ value: "productionManagerLineProducer", label: "Production Manager/Line Producer" },
	{ value: "screenwriter", label: "Screenwriter" },
	{ value: "scriptSupervisorContinuitySupervisor", label: "Script Supervisor/Continuity Supervisor" },
	{ value: "setDecorator", label: "Set Decorator" },
	{ value: "soundDesignerMixer", label: "Sound Designer/Mixer" },
	{ value: "specialEffectsSupervisor", label: "Special Effects (SFX) Supervisor" },
	{ value: "storyboardArtist", label: "Storyboard Artist" },
	{ value: "titleDesigner", label: "Title Designer" },
	{ value: "visualEffectsSupervisor", label: "Visual Effects (VFX) Supervisor" },
];
