export const languageSkills = [
	{ value: "nepali", label: "Nepali" },
	{ value: "hindi", label: "Hindi" },
	{ value: "english", label: "English" },
	{ value: "achhami", label: "Achhami" },
	{ value: "angika", label: "Angika" },
	{ value: "awadhi", label: "Awadhi" },
	{ value: "bajhangi", label: "Bajhangi" },
	{ value: "bajjika", label: "Bajjika" },
	{ value: "baitadeli", label: "Baitadeli" },
	{ value: "bantawa", label: "Bantawa" },
	{ value: "bengali", label: "Bengali" },
	{ value: "bhujel", label: "Bhujel" },
	{ value: "bhojpuri", label: "Bhojpuri" },
	{ value: "chamling", label: "Chamling" },
	{ value: "chepang", label: "Chepang" },
	{ value: "danuwar", label: "Danuwar" },
	{ value: "dhimal", label: "Dhimal" },
	{ value: "dotyali", label: "Dotyali" },
	{ value: "gurung", label: "Gurung" },
	{ value: "kham", label: "Kham" },
	{ value: "khaling", label: "Khaling" },
	{ value: "kurux", label: "Kurux" },
	{ value: "kulung", label: "Kulung" },
	{ value: "limbu", label: "Limbu" },
	{ value: "magahi", label: "Magahi" },
	{ value: "magar", label: "Magar" },
	{ value: "maithili", label: "Maithili" },
	{ value: "majhi", label: "Majhi" },
	{ value: "newari", label: "Newari" },
	{ value: "rajbanshi", label: "Rajbanshi" },
	{ value: "raji", label: "Raji" },
	{ value: "sampang", label: "Sampang" },
	{ value: "santhali", label: "Santhali" },
	{ value: "sherpa", label: "Sherpa" },
	{ value: "sunuwar", label: "Sunuwar" },
	{ value: "tamang", label: "Tamang" },
	{ value: "tajpuriya", label: "Tajpuriya" },
	{ value: "thangmi", label: "Thangmi" },
	{ value: "tharu", label: "Tharu" },
	{ value: "thulung", label: "Thulung" },
	{ value: "urdu", label: "Urdu" },
	{ value: "yakkha", label: "Yakkha" },
];

export const additionalSkills = [
	{ value: "dance", label: "Dance" },
	{ value: "singing", label: "Singing" },
	{ value: "musicalInstruments", label: "Musical Instruments" },
	{ value: "accentsDialects", label: "Accents and Dialects" },
	{ value: "martialArts", label: "Martial Arts" },
	{ value: "directing", label: "Directing" },
	{ value: "writing", label: "Writing" },
	{ value: "driving", label: "Driving" },
	{ value: "bikeRiding", label: "Bike Riding" },
	{ value: "swimming", label: "Swimming" },
	{ value: "athleticSports", label: "Athletic Sports" },
];

export const districts = [
	{ value: "kathmandu", label: "Kathmandu" },
	{ value: "achham", label: "Achham" },
	{ value: "arghakhanchi", label: "Arghakhanchi" },
	{ value: "baglung", label: "Baglung" },
	{ value: "baitadi", label: "Baitadi" },
	{ value: "bajhang", label: "Bajhang" },
	{ value: "bajura", label: "Bajura" },
	{ value: "bardiya", label: "Bardiya" },
	{ value: "bhaktapur", label: "Bhaktapur" },
	{ value: "bhojpur", label: "Bhojpur" },
	{ value: "chitwan", label: "Chitwan" },
	{ value: "dadeldhura", label: "Dadeldhura" },
	{ value: "dailekh", label: "Dailekh" },
	{ value: "dang", label: "Dang" },
	{ value: "darchula", label: "Darchula" },
	{ value: "dhading", label: "Dhading" },
	{ value: "dhankuta", label: "Dhankuta" },
	{ value: "dhanusha", label: "Dhanusha" },
	{ value: "dolakha", label: "Dolakha" },
	{ value: "dolpa", label: "Dolpa" },
	{ value: "doti", label: "Doti" },
	{ value: "gorkha", label: "Gorkha" },
	{ value: "gulmi", label: "Gulmi" },
	{ value: "humla", label: "Humla" },
	{ value: "ilam", label: "Ilam" },
	{ value: "jajarkot", label: "Jajarkot" },
	{ value: "jhapa", label: "Jhapa" },
	{ value: "jumla", label: "Jumla" },
	{ value: "kailali", label: "Kailali" },
	{ value: "kanchanpur", label: "Kanchanpur" },
	{ value: "kapilvastu", label: "Kapilvastu" },
	{ value: "kaski", label: "Kaski" },
	{ value: "khotang", label: "Khotang" },
	{ value: "lalitpur", label: "Lalitpur" },
	{ value: "lamjung", label: "Lamjung" },
	{ value: "mahottari", label: "Mahottari" },
	{ value: "makwanpur", label: "Makwanpur" },
	{ value: "manang", label: "Manang" },
	{ value: "morang", label: "Morang" },
	{ value: "mugu", label: "Mugu" },
	{ value: "mustang", label: "Mustang" },
	{ value: "myagdi", label: "Myagdi" },
	{ value: "nawalparasi", label: "Nawalparasi" },
	{ value: "nuwakot", label: "Nuwakot" },
	{ value: "okhaldhunga", label: "Okhaldhunga" },
	{ value: "palpa", label: "Palpa" },
	{ value: "panchthar", label: "Panchthar" },
	{ value: "parbat", label: "Parbat" },
	{ value: "parsa", label: "Parsa" },
	{ value: "pyuthan", label: "Pyuthan" },
	{ value: "ramechhap", label: "Ramechhap" },
	{ value: "rasuwa", label: "Rasuwa" },
	{ value: "rautahat", label: "Rautahat" },
	{ value: "rolpa", label: "Rolpa" },
	{ value: "rupandehi", label: "Rupandehi" },
	{ value: "salyan", label: "Salyan" },
	{ value: "sankhuwasabha", label: "Sankhuwasabha" },
	{ value: "saptari", label: "Saptari" },
	{ value: "sarlahi", label: "Sarlahi" },
	{ value: "solukhumbu", label: "Solukhumbu" },
	{ value: "sunsari", label: "Sunsari" },
	{ value: "surkhet", label: "Surkhet" },
	{ value: "syangja", label: "Syangja" },
	{ value: "tanahun", label: "Tanahun" },
	{ value: "taplejung", label: "Taplejung" },
	{ value: "tehrathum", label: "Tehrathum" },
	{ value: "udayapur", label: "Udayapur" },
	{ value: "westernRukum", label: "Western Rukum" },
	{ value: "sindhupalchok", label: "Sindhupalchok" },
	{ value: "sindhuli", label: "Sindhuli" },
	{ value: "siraha", label: "Siraha" },
];

export const companyTypes = [
	{ value: "Advertising Agency", label: "Advertising Agency" },
	{ value: "Casting Agency", label: "Casting Agency" },
	{ value: "Distribution Company", label: "Distribution Company" },
	{ value: "Equipment Rental Company", label: "Equipment Rental Company" },
	{ value: "Film Education Institution", label: "Martial Arts" },
	{ value: "Film Financing Company", label: "Film Financing Company" },
	{ value: "Film Festivals and Events Organization", label: "Film Festivals and Events Organization" },
	{ value: "Film Insurance Provider", label: "Film Insurance Provider" },
	{ value: "Film Production Company", label: "Film Production Company" },
	{ value: "Film Studio", label: "Film Studio" },
	{ value: "Legal and Clearance Service Company", label: "Legal and Clearance Service Company" },
	{ value: "Location Services Company", label: "Location Services Company" },
	{ value: "Post-Production Studio", label: "Post-Production Studio" },
	{ value: "Public Relations Agency", label: "Public Relations Agency" },
	{ value: "Streaming Platform", label: "Streaming Platform" },
];

export const genders = [
	{ value: "Male", label: "Male" },
	{ value: "Female", label: "Female" },
	{ value: "LGBTIQ", label: "LGBTIQ" },
];

export const ageGroups = [
	{ value: "Mid-60s", label: "Mid-60s" },
	{ value: "Early 60s", label: "Early 60s" },
	{ value: "Late 50s", label: "Late 50s" },
	{ value: "Mid-50s", label: "Mid-50s" },
	{ value: "Early 50s", label: "Early 50s" },
	{ value: "Mid-40s", label: "Mid-40s" },
	{ value: "Mid-30s", label: "Mid-30s" },
	{ value: "Early 30s", label: "Early 30s" },
	{ value: "Mid-20s", label: "Mid-20s" },
	{ value: "Early 20s", label: "Early 20s" },
	{ value: "Teenager", label: "Teenager" },
	{ value: "Pre-Teen", label: "Pre-Teen" },
	{ value: "Child", label: "Child" },
	{ value: "Infant", label: "Infant" },
];

export const filmDepartments = [
	{ value: "actor", label: "Actor" },
	{ value: "actionStuntCoordinator", label: "Action/Stunt Coordinator" },
	{ value: "animalTrainerHandler", label: "Animal Trainer/Handler" },
	{ value: "assistantDirector", label: "Assistant Director (1st AD, 2nd AD)" },
	{ value: "boomOperatorSoundRecordist", label: "Boom Operator/Sound Recordist" },
	{ value: "castingDirector", label: "Casting Director" },
	{ value: "cinematographer", label: "Cinematographer/Director of Photography (DP)" },
	{ value: "colorist", label: "Colorist" },
	{ value: "musicProducerComposer", label: "Music Producer/Composer" },
	{ value: "costumeDesignerWardrobe", label: "Costume Designer/Wardrobe" },
	{ value: "craftServiceCatering", label: "Craft Service/Catering" },
	{ value: "dialogueEditor", label: "Dialogue Editor" },
	{ value: "digitalEffectsArtist", label: "Digital Effects Artist" },
	{ value: "director", label: "Director" },
	{ value: "distributionCoordinator", label: "Distribution Coordinator" },
	{ value: "editor", label: "Editor" },
	{ value: "foleyArtistSoundEffectsEditor", label: "Foley Artist/Sound Effects Editor" },
	{ value: "gafferGrip", label: "Gaffer/Grip" },
	{ value: "locationManagerScout", label: "Location Manager/Scout" },
	{ value: "locationSoundMixer", label: "Location Sound Mixer" },
	{ value: "makeupHairStylist", label: "Makeup/Hair Stylist" },
	{ value: "marketingPublicityCoordinator", label: "Marketing/Publicity Coordinator" },
	{ value: "musicProducer", label: "Music Producer" },
	{ value: "postProductionSupervisor", label: "Post-production Supervisor" },
	{ value: "producer", label: "Producer" },
	{ value: "productionDesignerArtDirector", label: "Production Designer/Art Director" },
	{ value: "productionManagerLineProducer", label: "Production Manager/Line Producer" },
	{ value: "screenwriter", label: "Screenwriter" },
	{ value: "scriptSupervisorContinuitySupervisor", label: "Script Supervisor/Continuity Supervisor" },
	{ value: "setDecorator", label: "Set Decorator" },
	{ value: "soundDesignerMixer", label: "Sound Designer/Mixer" },
	{ value: "specialEffectsSupervisor", label: "Special Effects (SFX) Supervisor" },
	{ value: "storyboardArtist", label: "Storyboard Artist" },
	{ value: "titleDesigner", label: "Title Designer" },
	{ value: "visualEffectsSupervisor", label: "Visual Effects (VFX) Supervisor" },
];
