import "@/app/globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import AppHeader from "@/components/AppHeader";
import AppFooter from "@/components/AppFooter";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata = {
	title: "TeamForFilm | Home",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="h-full" suppressHydrationWarning>
			<body className={cn("relative min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
				<AppHeader />
				<main className="relative flex flex-col min-h-screen">
					<div className="flex-grow flex-1">{children}</div>
				</main>
				<AppFooter />
			</body>
		</html>
	);
}
