import "@/app/globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import AppHeader from "@/components/AppHeader";
import AppFooter from "@/components/AppFooter";

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata = {
	title: "TeamForFilm | Home",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="h-full dark" suppressHydrationWarning>
			<body className={cn("relative min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
				<div className="relative flex min-h-screen w-full flex-col">
					<AppHeader />
					<div className="flex-grow flex-1">sdfs</div>
					<AppFooter />
				</div>
			</body>
		</html>
	);
}
